### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by bodinsamuel** [algolia/npm-search#378]
Seems some update are not parsable. we should probably try/catch those.

```
Aug 05 14:16:58 npm-search app/worker.1: INFO:  🐌  Deleted @mobile-generator/mobile-generator 
Aug 05 14:17:00 npm-search app/worker.1: SyntaxError: Unexpected end of JSON input 
Aug 05 14:17:00 npm-search app/worker.1:     at JSON.parse (<anonymous>) 
Aug 05 14:17:00 npm-search app/worker.1:     at onSuccess (/app/node_modules/pouchdb-ajax/lib/index.js:41:20) 
Aug 05 14:17:00 npm-search app/worker.1:     at Request._callback (/app/node_modules/pouchdb-ajax/lib/index.js:101:7) 
Aug 05 14:17:00 npm-search app/worker.1:     at Request.self.callback (/app/node_modules/pouchdb-ajax/node_modules/request/request.js:187:22) 
Aug 05 14:17:00 npm-search app/worker.1:     at Request.emit (events.js:203:13) 
Aug 05 14:17:00 npm-search app/worker.1:     at Request.<anonymous> (/app/node_modules/pouchdb-ajax/node_modules/request/request.js:1126:10) 
Aug 05 14:17:00 npm-search app/worker.1:     at Request.emit (events.js:203:13) 
Aug 05 14:17:00 npm-search app/worker.1:     at IncomingMessage.<anonymous> (/app/node_modules/pouchdb-ajax/node_modules/request/request.js:1046:12) 
Aug 05 14:17:00 npm-search app/worker.1:     at Object.onceWrapper (events.js:291:20) 
Aug 05 14:17:00 npm-search app/worker.1:     at IncomingMessage.emit (events.js:208:15) 
Aug 05 14:17:00 npm-search app/worker.1: error Command failed with exit code 1. 
```

**Comment by Haroenv** [comment]
Those errors would be better if we could somehow get _some_ information there e.g. the string itself, so we can know how to fix it

**Comment by bodinsamuel** [comment]
No longer happening (at least not this particular error)
